name: "Build and push"

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ghcr.io/cristianhenzel/docker-mkiso:latest
          context: ./
          file: ./Dockerfile
          cache-from: ghcr.io/cristianhenzel/docker-mkiso:latest

      - name: Push
        run: docker push "ghcr.io/cristianhenzel/docker-mkiso:latest"
